# The Site Configuration

# Import the theme
theme: jekyll-theme-chirpy

# Change the following value to '/PROJECT_NAME' ONLY IF your site type is GitHub Pages Project sites
# and doesn't have a custom domain.
baseurl: ""

# The language of the webpage › http://www.lingoes.net/en/translator/langcode.htm
# If it has the same name as one of the files in folder `_data/locales`, the layout language will also be changed,
# otherwise, the layout language will use the default value of 'en'.
lang: fr

# Change to your timezone › https://kevinnovak.github.io/Time-Zone-Picker
timezone: Africa/Benin

# jekyll-seo-tag settings › https://github.com/jekyll/jekyll-seo-tag/blob/master/docs/usage.md
# ↓ --------------------------

title: foundhack # the main title

tagline: De la curiosité à la maîtrise | Hack, learn & share | From 0 to Hero # it will display as the sub-title

description: "Journal de Foundhack, explorateur passionné des CTF et de la cybersécurité. Partage, apprentissage et progression au fil des défis."

# fill in the protocol & hostname for your site, e.g., 'https://username.github.io'

url: "https://foundhack.github.io"

github:
  username: foundhack # change to your github username

twitter:
  username: foundhack # change to your twitter username

# ... [le début reste identique] ...

social:
  name: AGBIZOUNON CHAMSS-DINE
  email: foundhack119@gmail.com
  links:
    - https://github.com/foundhack
    - https://twitter.com/foundhack
    - https://www.linkedin.com/in/foundhack/
        - /feed.xml

# ... [le milieu reste identique] ...

# ↑ --------------------------
# Social icons configuration  
# ↓ --------------------------

social_icons:
  enable: true
  icons:
    - name: "GitHub"
      link: "https://github.com/foundhack"
      icon: "fab fa-github"
    - name: "Twitter"
      link: "https://twitter.com/foundhack"
      icon: "fab fa-twitter"
    - name: "LinkedIn"
      link: "https://www.linkedin.com/in/foundhack/"
      icon: "fab fa-linkedin"
    - name: "Email"
      link: "mailto:"
      icon: "fas fa-envelope"
    - name: "RSS"
      link: "/feed.xml"
      icon: "fas fa-rss"

# ... [la fin reste identique] ...

plugins:
  - jekyll-sitemap
  - jekyll-redirect-from
  - jekyll_plugin_logger
  - html-proofer

google_site_verification: # fill in to your verification string

# ↑ --------------------------
# The end of `jekyll-seo-tag` settings

google_analytics:
  id: 'G-N0BK6KLQXT' # fill in your Google Analytics ID

# Prefer color scheme setting.
#
# Note: Keep empty will follow the system prefer color by default,
# and there will be a toggle to switch the theme between dark and light
# on the bottom left of the sidebar.
#
# Available options:
#
#     light  - Use the light color scheme
#     dark   - Use the dark color scheme
#
theme_mode: dark # [light|dark]

# The CDN endpoint for images.
# Notice that once it is assigned, the CDN url
# will be added to all image (site avatar & posts' images) paths starting with '/'
#
# e.g. 'https://cdn.com'
img_cdn: "https://chirpy-img.netlify.app"

# the avatar on sidebar, support local or CORS resources
avatar: "/assets/img/avatar.png"

# boolean type, the global switch for TOC in posts.
toc: true

# Comments section completely removed

# Self-hosted static assets, optional › https://github.com/cotes2020/chirpy-static-assets
assets:
  self_host:
    enabled: # boolean, keep empty means false
    # specify the Jekyll environment, empty means both
    # only works if `assets.self_host.enabled` is 'true'
    env: # [development|production]

pwa:
  enabled: true # the option for PWA feature

paginate: 9

# ------------ The following options are not recommended to be modified ------------------

kramdown:
  syntax_highlighter: rouge
  syntax_highlighter_opts: # Rouge Options › https://github.com/jneen/rouge#full-options
    css_class: highlight
    # default_lang: console
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1

collections:
  tabs:
    output: true
    sort_by: order
  cheatsheets:
    output: true
    permalink: /cheatsheet/:name

defaults:
  - scope:
      path: "" # An empty string here means all files in the project
      type: posts
    values:
      layout: post
      comments: true # Enable comments in posts.
      toc: true # Display TOC column in posts.
      # DO NOT modify the following parameter unless you are confident enough
      # to update the code of all other post links in this project.
      permalink: /posts/:title/
  - scope:
      path: _drafts
    values:
      comments: false
  - scope:
      path: ""
      type: tabs # see `site.collections`
    values:
      layout: page
      permalink: /:title/
  - scope:
      path: assets/img/favicons
    values:
      swcache: true
  - scope:
      path: assets/js/dist
    values:
      swcache: true

sass:
  quiet: true
  style: compressed

compress_html:
  clippings: all
  comments: all
  endings: all
  profile: false
  blanklines: false
  ignore:
    envs: [development]

exclude:
  - "*.gem"
  - "*.gemspec"
  - docs
  - tools
  - README.md
  - CHANGELOG.md
  - LICENSE
  - rollup.config.js
  - node_modules
  - package*.json

jekyll-archives:
  enabled: [categories, tags]
  layouts:
    category: category
    tag: tag
  permalinks:
    tag: /tags/:name/
    category: /categories/:name/
